### ISSUE TITLE
Restrictions are added but not 'activated'

### ISSUE THREAD

**Issue by rdeveen** [mquekel/vsts-ip-restrictions#4]
The script is working, the IP restrictions are added and are visible in the Azure Portal but the restrictions are not working. When adding new restrictions in the portal, the already existing restrictions are activated and working. 

Maybe this is an issues with not using the latest version of the API? Can you update the task?

**Comment by mquekel** [comment]
Thanks for your comment. It has been a while since I have last updated this project. I will have a look at it and let you know!

**Comment by equalizer999** [comment]
OK, looks like the input for adding the IP addresses (including the range) is corrupting the complete functionality in the appservice :(. We added '1.1.1.1/1 API-management' from an Azure Pipeline which was successfully processed by the script and accepted as valid values in Azure. Just added '1.1.1.1' did the trick for getting it to work. Something to check; does a higher API version also have this behavior..?

**Comment by mquekel** [comment]
Thanks for the advide @rdeveen @equalizer999.
I fixed the issue by using the latest version of the API.
I upgraded the version to 3.0. If you want to use this new version, don't forget to upgrade the Version in your Azure Devops pipeline.
